# -*- coding: utf-8 -*-
"""il_calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1poyEmsvxtw6QiNmVlz1Dp2sclh-yaPEO
"""

import numpy as np
import matplotlib.pyplot as plt

def il_v2(r):
    r = np.asarray(r, dtype=float)
    return 2 * np.sqrt(r) / (1 + r) - 1

# Sanity checks
print(il_v2(1))    # should be 0
print(il_v2(2))    # about -5.72%
print(il_v2(0.5))  # same as r=2, IL is symmetric in log terms

# Plot IL vs price ratio
r = np.linspace(0.1, 5, 500)
plt.plot(r, il_v2(r) * 100)
plt.axhline(0, color="gray", lw=0.5)
plt.xlabel("Price ratio r = P_new / P_old")
plt.ylabel("Impermanent loss (%)")
plt.title("Uniswap v2 IL")
plt.show()

import numpy as np
import matplotlib.pyplot as plt

def v3_value_per_L(p, pa, pb):
    p = np.asarray(p, dtype=float)
    sp = np.sqrt(np.clip(p, pa, pb))
    x = 1 / sp - 1 / np.sqrt(pb)   # base token per unit L
    y = sp - np.sqrt(pa)           # quote token per unit L
    return x * p + y

def il_v3(p0, p1, pa, pb):
    p1 = np.asarray(p1, dtype=float)
    L = 1.0 / v3_value_per_L(p0, pa, pb)      # normalise start value to 1
    lp = L * v3_value_per_L(p1, pa, pb)
    sp0 = np.sqrt(p0)
    x0 = L * (1 / sp0 - 1 / np.sqrt(pb))
    y0 = L * (sp0 - np.sqrt(pa))
    hodl = x0 * p1 + y0
    return lp / hodl - 1

p0 = 1.0
p1 = np.linspace(0.3, 3, 600)

# Plot v2 vs v3
plt.figure(figsize=(10, 6))
plt.plot(p1, il_v2(p1 / p0) * 100, "k--", label="v2 (full range)")
for pa, pb in [(0.9, 1.1), (0.5, 2), (0.1, 10)]:
    plt.plot(p1, il_v3(p0, p1, pa, pb) * 100, label=f"v3 [{pa}, {pb}]")

plt.axhline(0, color="gray", lw=0.5)
plt.xlabel("Price (start = 1)")
plt.ylabel("IL vs HODL (%)")
plt.legend()
plt.title("IL: v2 vs v3 ranges")
plt.show()

print(f"IL v3 at start price: {il_v3(1, 1, 0.9, 1.1)}")  # should be 0

"""Fees vs IL"""

def liquidity_multiplier(p0, pa, pb):
    L3 = 1.0 / v3_value_per_L(p0, pa, pb)
    L2 = 1.0 / (2 * np.sqrt(p0))
    return L3 / L2

def net_return(p0, p1, pa, pb, fee_v2):
    """Net return vs HODL: IL + fees. fee_v2 = fee return a v2 LP earns over the period."""
    p1 = np.asarray(p1, dtype=float)
    m = liquidity_multiplier(p0, pa, pb)
    in_range = (p1 >= pa) & (p1 <= pb)
    v3 = il_v3(p0, p1, pa, pb) + np.where(in_range, fee_v2 * m, 0.0)
    v2 = il_v2(p1 / p0) + fee_v2
    return v2, v3

p0, fee_v2 = 1.0, 0.03   # assume 3% fee return for v2 over the period
p1 = np.linspace(0.3, 3, 600)

for pa, pb in [(0.9, 1.1), (0.5, 2), (0.1, 10)]:
    print(f"[{pa}, {pb}] multiplier = {liquidity_multiplier(p0, pa, pb):.1f}x")

v2, _ = net_return(p0, p1, 0.9, 1.1, fee_v2)
plt.plot(p1, v2 * 100, "k--", label="v2")
for pa, pb in [(0.9, 1.1), (0.5, 2), (0.1, 10)]:
    _, v3 = net_return(p0, p1, pa, pb, fee_v2)
    plt.plot(p1, v3 * 100, label=f"v3 [{pa}, {pb}]")

plt.axhline(0, color="gray", lw=0.5)
plt.xlabel("End price (start = 1)")
plt.ylabel("Net return vs HODL (%)")
plt.legend()
plt.title(f"Fees + IL, v2 fee return = {fee_v2:.0%}")
plt.show()

"""Real data: TVL and fee APY"""

import requests, pandas as pd
pools = requests.get("https://yields.llama.fi/pools").json()["data"]
c = [p for p in pools if p["project"] == "uniswap-v3" and p["chain"] == "Ethereum" and set(p["symbol"].split("-")) == {"USDC", "WETH"}]
for p in c: print(p["pool"], p["poolMeta"], p["tvlUsd"])

pid = [p["pool"] for p in c if p["poolMeta"] == "0.05%"][0]
h = requests.get("https://yields.llama.fi/chart/" + pid).json()["data"]
tvl = pd.DataFrame(h)
tvl["day"] = pd.to_datetime(tvl["timestamp"]).dt.date
tvl = tvl[["day", "tvlUsd"]].tail(90)
tvl.head()

import requests, pandas as pd
import matplotlib.pyplot as plt
pid = "665dc8bc-c79d-4800-97f7-304bf368e547"
h = requests.get("https://yields.llama.fi/chart/" + pid).json()["data"]
df = pd.DataFrame(h).tail(90).copy()
df["day"] = pd.to_datetime(df["timestamp"]).dt.date
df = df[["day", "tvlUsd", "apyBase"]]
print(df.isna().sum())
print(df.describe())
fig, ax = plt.subplots(2, 1, figsize=(8, 6), sharex=True)
ax[0].plot(df["day"], df["tvlUsd"] / 1e6)
ax[0].set_ylabel("TVL ($M)")
ax[1].plot(df["day"], df["apyBase"])
ax[1].set_ylabel("Fee APY (%)")
plt.xticks(rotation=45)
plt.show()

import numpy as np
end = int(pd.Timestamp.now().timestamp())
url = "https://coins.llama.fi/chart/coingecko:ethereum?end=" + str(end) + "&span=90&period=1d"
pr = requests.get(url).json()["coins"]["coingecko:ethereum"]["prices"]
px = pd.DataFrame(pr)
px["day"] = pd.to_datetime(px["timestamp"], unit="s").dt.date
px = px.groupby("day")["price"].last().reset_index()
m = df.merge(px, on="day")
print(len(m))
print(m[["day", "price"]].iloc[[0, -1]])

p0 = m["price"].iloc[0]
price = m["price"].values
fday = m["apyBase"].values / 100 / 365
v2_il = float(il_v2(price[-1] / p0))
v2_fees = fday.sum()
print("v2 IL", v2_il, "fees", v2_fees, "net", v2_il + v2_fees)
res = pd.DataFrame({"width": [0.05, 0.2, 0.5]})
res["pa"] = p0 * (1 - res["width"])
res["pb"] = p0 * (1 + res["width"])
pairs = list(zip(res["pa"], res["pb"]))
res["mult"] = [float(liquidity_multiplier(p0, a, b)) for a, b in pairs]
res["in_range"] = [((price >= a) & (price <= b)).mean() for a, b in pairs]
res["fees"] = [(fday * ((price >= a) & (price <= b))).sum() * k for (a, b), k in zip(pairs, res["mult"])]
res["il"] = [float(il_v3(p0, price[-1], a, b)) for a, b in pairs]
res["net"] = res["il"] + res["fees"]
print(res[["width", "mult", "in_range", "fees", "il", "net"]])

ws = np.arange(0.02, 1.01, 0.02)
nets = []
for w in ws:
    a, b = p0 * (1 - w), p0 * (1 + w)
    k = float(liquidity_multiplier(p0, a, b))
    inr = (price >= a) & (price <= b)
    f = (fday * inr).sum() * k
    nets.append((float(il_v3(p0, price[-1], a, b)) + f) * 100)

plt.plot(ws * 100, nets, label="v3 net")
plt.axhline((v2_il + v2_fees) * 100, color="k", ls="--", label="v2 net")
plt.xlabel("Range half-width (%)")
plt.ylabel("Net return vs HODL (%)")
plt.legend()
plt.savefig("range_sweep.png", dpi=150)
plt.show()